### ISSUE TITLE
Agents won't move after using initialize() the second time

### ISSUE THREAD

**Issue by Eisendroid** [TheSHEEEP/godotdetour#4]
Godot: 3.2.3 stable
OS: Linux Manjaro
Kernel: 5.4.67-1

When i start my program and do the whole initialization, everything works fine.

When i try do rebuild everything in same session ( with clear() and initialize() ) on the same DetourNavigation, something goes wrong. Everything seems to be ok, but the Agents won't move this time.

The Agents always return:
DetourNavigation.isMoving = false
DetourNavigation.velocity = (0,0,0)
DetourNavigation.target = _correct target position_ <- at least the Agent knows where he should be going

No errors are given and Mesh seems to be created (debugMesh shows up). I tried to set the navigation to null and do DetourNavigation.new() again, but that will result in a crash. I tried to find the solution by myself, but i have a hard time because i have no experience with c++.

**Comment by TheSHEEEP** [comment]
The agents are upset that you took their navigation away (they liked it better than the new one) and refuse to do any more work ;)

Yes, that does sound like a bug, or multiple ones even (creating a .new() Navigation should definitely not crash, no matter what you do with the first one).
  
Assuming you are not using the same agents? Clearing the Navigation will also remove all agents - any agents still around in GDScript would then be invalid ones.

I'll have a look at it probably next Monday.

In the meantime, some more explanation might help.  
What are you trying to achieve clearing and rebuilding everything within a session? In the demo, there is already an example of saving, clearing, and then loading again to restore the state.

**Comment by Eisendroid** [comment]
> Yes, that does sound like a bug, or multiple ones even (creating a .new() Navigation should definitely not crash, no matter what you do with the first one).

I tried it in the Demo and it also leads to a crash.

> Assuming you are not using the same agents? Clearing the Navigation will also remove all agents - any agents still around in GDScript would then be invalid references.

Yes, anything related to the old Agents is freed from the scene. The new ones are freshly spawned into the scene.

> What are you trying to achieve clearing and rebuilding everything within a session?

My game is heavily based on a random world generator, so everytime the player starts a new game, everything old is going to be deleted (except some tiny global scripts) and a new world is created. That's the weird thing, because the first time, it works perfect, but the second time i generate the world, the Agents won't move. It seems like the initialize() function changes some variables the first time i use it and this behaviour is heavily influencing the second use of it.

>  In the demo, there is already an example of saving, clearing, and then loading again to restore the state.

It works like it should. I implemented a simple version of saving/clearing/loading in my game, and it seems to work great. That's the reason i think the clear() function is working and the problem is more likely to be initialize()

> Also, is this reproducible in the demo? If not, what's the difference?

Yes, it is. .new() of DetourNavigation leads to crash, initialize() leads to Agents who won't move.


I have tested a lot of things so far and i am running out of ideas right now. If you want me to test something, i will do my best. Thanks for your effort! Your module is important to me, so i will help you as much as i can.

**Comment by TheSHEEEP** [comment]
One thing I have found out so far is that it is the assignment of the old Navigation instance that causes a crash. At least for me.
For example:

```
navigation = DetourNavigation.new()
# Initialize, use, etc.
navigation.clear()
navigation = DetourNavigation.new() # <---- crash
navigation = null <------ also crash
navigation = 33 <---- also crash
```
So no matter what you assign to it, it will crash. When you create a completely new variable for it, it won't crash:

```
navigation = DetourNavigation.new()
# Initialize, use, etc.
navigation.clear()
var navigation2 = DetourNavigation.new() # <---- no crash
```

That might at least be a workaround while I figure out wtf is going on there :sweat_smile: .

**Comment by TheSHEEEP** [comment]
Alright, some good news, I was able to fix the crash upon re-assignment of the Navigation instance.
It turned out to simply be some cleanup mistake in clear() and the destructor (which gets called upon re-assignment of the instance).
Took some playing around with valgrind and valkyrie, so that's always fun ;)

Unfortunately, I need to tackle some other things now so I'll have to investigate the second problem (Agents not moving) another time, hopefully this week still.

**Comment by Eisendroid** [comment]
Thx for the good work! c810d97e88f70ff6424a6356d515ac7658737c31 already fixes the non moving Agents bug, considered i do .new() of DetourNavigation. If i use initialize() alone, it still won't work.

Just take your time. :) The current solution is a good workaround for now (at least for me).

**Comment by TheSHEEEP** [comment]
Huh! Interesting. I guess the non-moving agents were at least partly affected by that bug as well.
Well, that's a nice coincidence.

Will still check what is wrong with the 2nd initialize() not working properly.

**Comment by TheSHEEEP** [comment]
Should be fixed now with the latest commit.
As usual, it was a totally dumb mistake: not resetting the variable that stops the navigation thread - so on subsequent initialize()s the navigation thread would start and immediately stop, not doing any actual navigation...
